# Generated by Django 3.1.5 on 2021-04-16 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boroughcode', models.CharField(max_length=64, verbose_name='자치구 코드')),
                ('boroughname', models.CharField(max_length=64, verbose_name='자치구명')),
            ],
            options={
                'db_table': 'Borough',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finecode', models.CharField(max_length=64, verbose_name='과태료 코드')),
                ('finename', models.CharField(max_length=64, verbose_name='과태료 이름')),
                ('finecontents', models.CharField(max_length=100, verbose_name='위반내용')),
                ('fine', models.IntegerField(verbose_name='과태료')),
            ],
            options={
                'db_table': 'Fine',
            },
        ),
        migrations.CreateModel(
            name='SmokingAreaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typecode', models.CharField(max_length=64, verbose_name='유형 코드')),
                ('typename', models.CharField(max_length=64, verbose_name='유형 이름')),
            ],
            options={
                'db_table': 'SmokingAreaType',
            },
        ),
        migrations.CreateModel(
            name='SmokingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.CharField(max_length=64, verbose_name='구역 코드')),
                ('address', models.CharField(max_length=150, verbose_name='주소')),
                ('boroughcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borough_smoking', to='smoking.borough')),
                ('typecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoking_type', to='smoking.smokingareatype')),
            ],
            options={
                'db_table': 'SmokingArea',
            },
        ),
    ]
